### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by SUNGOD3** [ragntune/code-llama-finetune#3]
Hello, I tried to execute this code but the following error occurred when training (it seems to have only appeared in the past few days, there was no problem before):
OutOfMemoryError: CUDA out of memory. Tried to allocate 64.00 GiB. GPU 0 has a total capacty of 14.75 GiB of which 5.48 GiB is free. Process 15367 has 9.27 GiB memory in use. Of the allocated memory 8.79 GiB is allocated by PyTorch, and 351.89 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by SUNGOD3** [comment]
This problem seems to be solved by modifying the per_device_train_batch_size parameter, although the execution time will be significantly extended.

But what I am curious about is why the usage of CUDA memory has increased?
